#!/bin/sh

query=$(printf "" | dmenu -p "Search: " | sed 's/\ /+/g' )
videos=$(curl -sL "https://www.youtube.com/results?search_query=${query}" | sed 's/},{/\n/g' | sed -nE 'N;N; s@.*\"videoRenderer\":\{\"videoId\":\"([a-zA-Z0-9_-]{11})\".*\"title\":\{\"runs\":\[\{\"text\":\"(.{1,100})\"\}\],.*@www.youtube.com/watch?v=\1 | \2@p')
url=$(printf "${videos}" | dmenu -i -l 5)
[ -z "${url}" ] && exit
${BROWSER} $(printf "${url}" | grep -Po '^.{35}')
